AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create and deploy an AWS Lambda function

Resources:
  MyLambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "greeting-timestamp-lambda_3_cloud_formation"
      Runtime: "python3.13" # Change to your preferred runtime
      Handler: "lambda_function.lambda_handler" # Modify as needed
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Code:
        S3Bucket: "my-lambda-deployment-bucket-yaron" # Replace with your S3 bucket name
        S3Key: "path/to/your/lambda-code.zip" # Replace with your zip file path
      Timeout: 10
      MemorySize: 128

Outputs:
  LambdaFunctionName:
    Description: "The name of the Lambda function created."
    Value: !Ref MyLambdaFunction
